### ISSUE TITLE
Sponsor workflow updates

### ISSUE THREAD

**Issue by jameslockman** [arthurlockman/gatool-ui#121]
There have been cases where sponsors have changed, but we aren't tracking that. 
Please remove the ability to edit the complete sponsors list
Please also provide a button to refresh the top sponsors from the calculated top sponsors

**Comment by dgconder** [comment]
I know we are only supposed to read the top 2 or so sponsors. Some have really long names. I would like the ability to mark off the ones I have read. So next time around I skip that one.  After a couple times through I should have read all the top sponsors and not awkwardly held up the show trying to read too much in one pass. Probably should have logged a separate instance. But It does kind of go with sponsor work flow.

**Comment by jameslockman** [comment]
Thanks, Daniel.
We are pushing a fix to this issue this evening, that will lock the full sponsors list while adding text about how to reset the sponsors list to the "factory" value. Users can copy and paste from the TIMS value to the top sponsors field.

Your suggestion is different. Here (in New England), we read the top 5 sponsors the first time a team comes to the Driver's station. When we see rankings for the team, we stop reading their sponsors. When all teams are through, we shut off the sponsors altogether. Please create a new issue for this, so that we can track it separately.
