### ISSUE TITLE
Heading Font Size

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#220]
Consider reducing the font size (and changing the style) for H1 and H2 for the HTML fields.

**Comment by jameslockman** [comment]
The current implementation results in this for headers. It also appears we did not implement font sizes properly.
![Cursor_and_FIRST_Game_Announcer_Tool_and_FIRST_Game_Announcer_Tool](https://github.com/arthurlockman/gatool-ui/assets/2659225/634a015e-03c0-4650-9ae4-cbab3a93d0ba)


We propose the following, with the addition of color controls for the Team Data screen notes. We tested color on Announce and Play By Play, and we dont' think there's a good balance that's readable for both red and blue alliance presentation.
![FIRST_Game_Announcer_Tool](https://github.com/arthurlockman/gatool-ui/assets/2659225/d102fa57-618a-4e4a-b71b-e737afb08e63)
