### ISSUE TITLE
Team Entry Keystrokes

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#229]
<Just a recommendation> It would, in my opinion, be easier to enter teams manually for a match in "Configure Teams for Match" if we could just start in Red1, enter the number, hit tab, enter the Red 2 number, hit tab, enter the Red 3 number, hit tab, enter the Blue 1 number etc..

**Comment by jameslockman** [comment]
Is this for the ad hoc match?

**Comment by WBAucoin** [comment]
Yes

**Comment by jameslockman** [comment]
The reason we need to configure is that the view renders when it has a team. I suppose I could lead with the form if there is no fully populated match. Let me think about it.

**Comment by jameslockman** [comment]
There are also conditions when there are not 6 teams on the field for a practice match. Including a test for an incomplete match would be difficult in that scenario. We can test for the case when all teams are null, and if so, open the dialogue. @WBAucoin Would that be a reasonable compromise?

**Comment by jameslockman** [comment]
Closed by #243
