### ISSUE TITLE
Cannot Clear Out Wrong Team Number

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#231]
When I try to enter in a team number (which for Week0) is not in the team listing, the team number for the previous match is retained in the system with no way to clear it out (set it to a null value). In Qualification Match 12, 3117 is in Blue 3. GA tool is stuck on Team 58 (for me) with no means to make it go away.

**Comment by jameslockman** [comment]
Was this before or after resetting the cache?

**Comment by WBAucoin** [comment]
Before clearing the cache.

**Comment by jameslockman** [comment]
Did a cache reset clear this issue?

**Comment by WBAucoin** [comment]
I’ll have to check when I get home. I suspect not.

**Comment by jameslockman** [comment]
And to be clear, this is for subbing a team in playoffs?

**Comment by WBAucoin** [comment]
I thought it was for the ad hoc “test match” where you entered ALL the
teams. I’ll have to check again.

The issue was identified “pre-clearing cache” so I was manually entering
the teams. ( The next match and previous match buttons did not exist.)

Bill

**Comment by jameslockman** [comment]
Thanks. There are no Next and Previous match buttons on the Test Match screen. We'll be pushing a change that fixes some cosmetics on that screen, adds a "none" choice, ensures that a team cannot occupy more than one driver's station, and reverses the red and blue color. 
<img width="1177" alt="FIRST_Game_Announcer_Tool" src="https://github.com/arthurlockman/gatool-ui/assets/2659225/19c2bbe4-fa54-4914-84b9-e7e33e0cbd28">

**Comment by WBAucoin** [comment]
Nice job. I tested it and it works great. There is now a "None" selection in test match that did not exist before.
