### ISSUE TITLE
Auto Advance Behind and Fighting You

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#234]
During Week 0 and during the team introductions for Qualification 16, GA tool was on Match 15 with the auto advance set to advance (Automatically track event progress, refreshing every 30 seconds (will advance matches on all screens)). When I tried to manually advance to match 16, it moved me right back to Match 15 (the match which just finished).

**Comment by jameslockman** [comment]
Auto Advance depends on getting data from the scoring system to validate that matches have been completed. We have seen several cases where the scoring system has significant delays when requesting data from the APIs. Most critically, the playoff scores often seem to take longer than we would like to appear when we ask for them. Unfortunately, we cannot control this, so the feature may not be useful for all scenarios.

**Comment by WBAucoin** [comment]
The logic to advance to the next match is not working. gatool knows that the next match is over but it does not want to advance to it. Is the issue a "N+1" calculation issue? It seems to want to go to the last match that has been **completed**.
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/f1db79af-e136-4a41-b848-f8a6a3449268)
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/83d3ea0c-ccc3-448f-928c-20f8e99b1933)

**Comment by WBAucoin** [comment]
... or perhaps we are not getting updates. Match 20 is underway and gatool thinks 16 is next.

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/825415df-5941-4086-b249-82bc336cb21c)

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/ded04d9f-5cdf-45a6-be91-e209a012dfd9)

**Comment by WBAucoin** [comment]
Checking the beta version and watching FIRST CHS Ashland, the advancing is still slightly behind what I would prefer. The emcees IRL are announcing the teams before the gatool advances to the next match.
