### ISSUE TITLE
Duplicate High Scores

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#235]
During Week 0, Qualification 3 was listed as the high score for both the "no penalties" and "with penalties" scores.
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/b399b080-4b06-4020-a357-0b38ab3c7f54)

**Comment by jameslockman** [comment]
This is as expected. Including penalties means matches with and without penalties or all matches.

**Comment by WBAucoin** [comment]
I would not have expected that. I would assume that one was *purely* clean
and one was augmented by penalties (“not clean”).
