### ISSUE TITLE
Flash Cards - MC Pronunciations?

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#236]
Not a biggie. The MC pronunciations are on the front side of the flash cards on the cheat sheet. I would just show the team number. It would be logistically impossible, but if there were a way to show a picture of the current season robot that would be perfect!

**Comment by jameslockman** [comment]
It is logistically possible, and we're pushing the addition of robot images now.

**Comment by WBAucoin** [comment]
No freakin way! 😲

**Comment by WBAucoin** [comment]
I am not seeing the pictures on the front side of the cards. Just the numbers.

**Comment by jameslockman** [comment]
Are you certain there are photos for the teams at your event? Check with TBA, which is the source.

**Comment by jameslockman** [comment]
![FIRST_Game_Announcer_Tool](https://github.com/arthurlockman/gatool-ui/assets/2659225/d7877633-d74d-48f9-8f0d-4ef0496174c8)

**Comment by WBAucoin** [comment]
Possibly not. I was using Week0.

**Comment by jameslockman** [comment]
Images are not appearing consistently due to timing. Please fix.

**Comment by WBAucoin** [comment]
FRC 3357 is a good test case (and it is working well). They have 2024 media in TBA.
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/3dcd0de1-6971-4432-9076-f226320c509c)
