### ISSUE TITLE
EMCEE Numbers Too Big on iPAd

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#241]
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/f9ed6d18-9249-4642-b5e7-30a4fc22a732)
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/337a27a6-2056-4fc2-b293-0105d87580b7)

**Comment by jameslockman** [comment]
This was designed for horizontal view. We can try to come up with something that works vertically.

**Comment by WBAucoin** [comment]
The scaling is too big for **either** orientation on an iPad mini:

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/8207f29f-0f53-4f71-98fb-16ebceee7825)
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/a55ebc82-adb0-4b79-9777-11a660e4b170)
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/eb00c975-353f-4649-bc71-5aa11bcf4be4)
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/f240a001-ba1d-4b97-ba95-cee0aca833ad)

**Comment by WBAucoin** [comment]
Looking much better on iPad mini in landscape mode. It does have a funky bug where, if you start in the playoffs and swipe backwards to the qualification matches, you get a tiny number and you cannot swipe back to the playoffs.![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/fed2d493-c7ce-4181-a4d7-e5b240309fa5)
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/d1d241d0-9dd6-4500-b1c7-7788b177cf02)
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/676cb87b-403b-4a81-bc65-e988f2027a3b)
