### ISSUE TITLE
Cheat Sheet not opening on iPad mini

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#245]
The cheat sheet opens a blank page right now. ![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/9f47f7ed-2f94-45c6-8514-86cf4a774400)

**Comment by jameslockman** [comment]
Please reset the cache.

**Comment by jameslockman** [comment]
Investigating.

**Comment by jameslockman** [comment]
Closed with #247
