### ISSUE TITLE
MC/GA Contact Info, Communications and Read/Write Privileges

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#246]
As an enhancement, could we provide an entry where the MCs and GAs assigned to an event can self-identify themselves and either provide contact information and/or a means to initiate communications? Having a hyperlink that opens a new email to the assigned volunteers would be excellent. Auto populating the subject line of the email ("GA/MC Coordination for <Put Event Name and Date Here>") would be an added bonus.

As slick option, we could make the GA tool read only for an event in which the user has not self-identified as an assigned MC/GA and editable for MCs and GAs who have self-identified as being assigned to the event.

This would be an opt-in feature and we might want to filter the entered contact data to the contact data used for logging into the game tool.

The rationale is to see who is assigned for the purposes of coordinating gatool updates. The assignment of volunteers is closely-held PII which is commonly not released to the other volunteers. For example, I am assigned to the PCH District Charleston event and the VC has promised, but not provided, the names of the other MCs & GAs. I cannot coordinate the update of the GA Tool right now since I don't have the ability to contact them.

If we did this, we might want to validate the list of folks with valid log in credentials periodically. This would prevent a former and not current user from accessing the PII that we are now putting in gatool.

**Comment by jameslockman** [comment]
This should be managed by the Volunteer Coordinators. Also, we don't want to be in the business of matchmaking or storing too much personal information beyond the self-populated and email address, which is what we keep now.
