### ISSUE TITLE
No Events to Select on iPhone

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#268]
No events were available for selection with an iPhone. I could not replicate it with an iPad

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/7b616c88-6ffd-44fc-89b3-6b99dc3eadbd)

**Comment by jameslockman** [comment]
Not reproducible here. Reload or clear web cache.

**Comment by WBAucoin** [comment]
Cleared cache/website data and the issue resolved itself.
