### ISSUE TITLE
Regional Name Transposed

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#274]
This is likely a FIRST HQ and API issue, but the name of the regional in Port Hueneme has the words in the name transposed.
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/da00ee43-53ba-4fc7-a0bf-c137e7e30548)

**Comment by jameslockman** [comment]
Yes, that is what we're [getting from FIRST](https://frc-events.firstinspires.org/2024/Events/EventList).
![FRC_Event_Web___2024_Season_Event_List](https://github.com/arthurlockman/gatool-ui/assets/2659225/416b3b2b-36ab-4e06-b640-83c4b09aef77)

**Comment by WBAucoin** [comment]
I assumed that was the reason. Thanks!
