### ISSUE TITLE
Enhancement Request: Teams Frozen in Alliance Selection

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#275]
In a future update, consider color coding the team number when it is frozen in alliance selection (similar to the way you code the teams who decline an invitation).

1. Initially, only the #1 seeded team would be color coded thusly.
2. After #1 picks their first alliance partner, that team is now color coded along with the #1 alliance captain AND the #2 alliance captain.
3. etc. etc.

This way it is easier to determine that an alliance who is not paying attention, tries to select a team that is already selected.

Cosmetic... not needed... would be cool.

**Comment by jameslockman** [comment]
I am having difficulty following this. If they've been picked, they end up on an Alliance. Those teams are removed from the pink area, which contains all of the available teams.

**Comment by WBAucoin** [comment]
Good point. I was thinking in the listing of the alliances on the right hand side of the screen.
