### ISSUE TITLE
Feature request: show notes on Announce but not Play-by-Play

### ISSUE THREAD

**Issue by wortzmanb** [arthurlockman/gatool-ui#280]
I generally prefer to keep play-by-play very clean to fit on a smaller screen, but I'd still like to be able to see notes on Announce for intros or to switch to on occasion. Could we separate these options?

**Comment by wortzmanb** [comment]
Well that was fast! Thanks, @jameslockman!

**Comment by jameslockman** [comment]
It will appear after events end tomorrow. You can see it active now at https://beta.gatool.org
