### ISSUE TITLE
404:Backend Error

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#286]
Got this when logging into an event.
![Uploading IMG_7293.png…]()

**Comment by WBAucoin** [comment]
I was on a commercial airplane at the time if that helps.

**Comment by jameslockman** [comment]
We do not guarantee gatool will work under these conditions.

**Comment by jameslockman** [comment]
This was caused by requests being sent before we had any event data. This error should no longer appear after #288
