### ISSUE TITLE
Alliance backup team picked up as a "3rd pick"

### ISSUE THREAD

**Issue by timtim17** [arthurlockman/gatool-ui#292]
During playoffs we had an alliance utilize their backup coupon. The scorekeeper entered the backup team into the FMS.

👍🏻 Good thing: GATool picked up the new team automatically, without needing to interact with the "backup" button. 🎉 (Not sure if this was an intended feature, but pretty nifty).

👎🏻 The backup was added to the alliance as a fourth robot, shown at the bottom of the of the announce/play-by-play pages as their "Round 3 selection," with the opposing alliance being shown as "No fourth alliance member."

This could be completely intended, as in this case we can still see the information about the replaced alliance member so we can acknowledge them as part of the alliance. But, it still seems a little odd to have all this about them being the "3rd pick." Was told to capture this and send it in.

![image](https://github.com/arthurlockman/gatool-ui/assets/6354860/eeffe62a-f8d2-432a-a0f9-23a52e5c3e54)

2024waahs Alliance 2

**Comment by jameslockman** [comment]
This is as designed. The language actually comes from FIRST Champs, where there are 4 robots per Alliance. And now, the backup alliance member is technically the fourth Alliance member.
