### ISSUE TITLE
Announce and play-by-play not loading in offline mode

### ISSUE THREAD

**Issue by wortzmanb** [arthurlockman/gatool-ui#302]
I am currently unable to see teams on announce and play-by-play when operating in offline mode. Schedule and team lists are loaded correctly.
<img width="1128" alt="image" src="https://github.com/arthurlockman/gatool-ui/assets/8575915/1df8ca89-e781-4991-9a29-e3b10d9326a4">
<img width="1128" alt="image" src="https://github.com/arthurlockman/gatool-ui/assets/8575915/6b130efd-6a59-4e79-a4ed-f386d9a4ae71">
<img width="1128" alt="image" src="https://github.com/arthurlockman/gatool-ui/assets/8575915/034bdc20-55bf-430b-ab95-850566191767">
<img width="1128" alt="image" src="https://github.com/arthurlockman/gatool-ui/assets/8575915/296bd215-a155-4248-9280-c4a079a61a47">

**Comment by jameslockman** [comment]
Please reset your cache. We believe we fixed this in a PR a few mins ago. Playoff matches still not loading and Test Match not working, but will later.

**Comment by wortzmanb** [comment]
None of clearing the browser cache, clearing the gatool page cache, or opening an InPrivate tab seem to have solved the problem. Do I need to clear cookies as well?

**Comment by wortzmanb** [comment]
FYI, I was still seeing this behavior even after this fix. I was able to repro it in a browser that had never run gatool on my machine before, so it shouldn't be a cache issue. Lower pri now for me, as my event is back online from the FIRST API.

**Comment by jameslockman** [comment]
Let us know if it’s still there after the later updates.

**Comment by WBAucoin** [comment]
OK.Later….
Everything is working well in normal mode. I don’t want to mess anything up.

Bill
