### ISSUE TITLE
Unable to Launch Test Match Mode

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#309]
At the 2024 Week 3 FIRST CHS Severn District Event, we did were not able to get Test Match to work. We would move the switch to activate Test Match. When we went to Announce or Play by Play, we would get a blank browser window.

**Comment by jameslockman** [comment]
Can you please provide more detail? We had patched this condition yesterday afternoon.

**Comment by WBAucoin** [comment]
Yes, but I'd have to break out the laptop that we used at the event. Can I
do that later? I am very tired right now. That was a crazy event (mainly
fun crazy).

Bill

**Comment by jameslockman** [comment]
We tested here and were able to produce a crash condition, but it resolved to the set test match menu. We will investigate.

**Comment by WBAucoin** [comment]
Would you like me to show you my symptoms? I’d be willing to screen share
and give it a try.

**Comment by WBAucoin** [comment]
On a related note, the ability to do team substitutions in *OFFLINE* mode
would have been useful today. We were in playoffs and had a substitution.
We addressed that with a 3x5 card taped to the side of the monitor.
