### ISSUE TITLE
[Enhancement] Add Substitutes to ***OFFLINE*** Mode

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#311]
At the 2024 FIRST CHS Severn District event, the FMS would not report the alliances in the playoffs outside of the venue. The MC/GA team used ***OFFLINE*** mode for the entirety of the playoffs. When a substitute was called by the #1 alliance, there was no way to substitute the alliance team and enter the backup team.

**Comment by jameslockman** [comment]
This is true: Offline mode does not recognize Playoff Matches as being special. We will evaluate a fix.
