### ISSUE TITLE
[Enhancement] Add Playoff Smarts to ***OFFLINE*** Mode

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#312]
Some of the normal playoff-specific information provided to the MC/GA during playoffs are not provided when the gatool ingested a FMS schedule export into the ***OFFLINE*** mode. If there is a way to have the gatool detect that the FMS has exported a **_playoff set_** of matches and add that additional information to the gatool display, it would enhance the ability to conduct the color commentary on the playoff matches.

**Comment by jameslockman** [comment]
Offline supports this model already:
Upload Quals Matches first
![FIRST_Game_Announcer_Tool](https://github.com/arthurlockman/gatool-ui/assets/2659225/6e690481-a019-4123-b481-1990dd402203)

Upload Playoff Matches second
![FIRST_Game_Announcer_Tool](https://github.com/arthurlockman/gatool-ui/assets/2659225/f81a12dd-d7c5-4d3f-8ee6-5380e5368bde)

**Comment by WBAucoin** [comment]
This assumes you are *starting* as an offline event. At 2024’s FIRST CHS
Severn event, we started with OFFLINE, went to FMS/API data then, in then
for the PLAYOFFS, had to go back to OFFLINE.

If this is the normal CONOP, training needs to be held or a dialog warning
box provided, to notify the user that the Qual Schedule has to be loaded
before the Playoff schedule.

**Comment by klardotsh** [comment]
Huge +1 to this, or something like it.

[I commented in 282](https://github.com/arthurlockman/gatool-ui/issues/282#issuecomment-2002069274) a complimentary option I would have appreciated, which is simply the ability to scribble in my own rankings for alliance selection. Then, it would be nice to be able to punch in my own alliances for what had previously been an online event, for example in the case that FIRST API breaks mid-event.

At PNW Sundome, I was in online mode most of the event, but the FIRST API gave up any hope of stability while we were running playoffs, leading to sporadic updates (up to and including a "wrong" advancement - we had to replay a playoffs match that had been committed but not posted; GATool learned about the commit but not the replay and so the resulting match with the winner of the replay had an eliminated alliance shown as playing). My eventual solution was to have my FTA print me paper announcer reports for Match 11 and beyond. It was messy. I'm sure any code fix to support hybrid online-offline events is also going to be messy, but I think this past week is some evidence that it's a usecase worth considering.

**Comment by jameslockman** [comment]
@klardotsh can you please open a new issue for this? We addressed the initial question with existing functionality, but yours is a new feature request for manual rankings.
Is there a reason why uploading a ranking report from FMS, which we know to be correct?

**Comment by klardotsh** [comment]
Sure, I'll circle back to a new issue shortly-ish.

Regarding why: honestly it's just a speed/efficiency thing. If I'm already jotting down the numbers for alliance selection anyway, it's fast for me to type team numbers in to set alliances and then use cached team data for playoffs announcing (assuming FIRST API is down), as compared to digging up my USB stick, bothering my FTA who is busy doing any number of playoffs prep tasks (or chatting with FIRST support, or whatever), and then doing the XLS import dance. To type 24 maximally-5-character integers takes me under a minute and bothers nobody.
