### ISSUE TITLE
[Enhancement] Add ***OFFLINE*** Mode Button to the Setup Screen

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#313]
The ***OFFLINE*** match setting seems a bit hidden from the operator within the GUI. Consider moving it to the setup screen where the operator can access it directly (and not wade through a semi-endless list of regionals and district events). Consider making the Test Match and Offline Mode buttons/switches similar in operation also.

**Comment by jameslockman** [comment]
We considered this originally, but using an OFFLINE event allowed us to re-use existing event load code rather than create new handlers for the condition.

**Comment by WBAucoin** [comment]
OK. It works.

We should emphasize how to get there in future training. I must have slept
through that part. It took me awhile to find it.

Bill

**Comment by jameslockman** [comment]
We sent an email in the Spring at the start of the offseason explaining how to use OFFLINE event mode. We can do that again this week as a reminder.

**Comment by WBAucoin** [comment]
I would recommend that. While I might be a single point example of
ineptness, it would likely be good to send a reminder. I’d also verbally
mention it in any GA/MC calls.

Bill
