### ISSUE TITLE
Issue With Practice Match Schedules

### ISSUE THREAD

**Issue by kleium** [arthurlockman/gatool-ui#315]
I uploaded a practice match schedule as an excel document. For a brief moment, it all worked fine and I was able to play around the schedule. Though afterwards the page immediately became blank, and I couldn't get to reload it. Then I tried to get a practice match schedule running on a different device, and things ended up the same way. 

I would appreciate if you could look into it.

**Comment by jameslockman** [comment]
Can you please specify which event? Also, can you please provide the practice schedule itself?
Was this before or after last night’s updates?

**Comment by kleium** [comment]
Haliç Regional. I have attached the schedule. It happened after the update.
[TUHC2024_ScheduleReport_Practice.xlsx](https://github.com/arthurlockman/gatool-ui/files/14649770/TUHC2024_ScheduleReport_Practice.xlsx)

**Comment by jameslockman** [comment]
We are able to reproduce. It appears that FMS was not reporting team data, so it was impossible to render the announce and play by play pages. This has resolved at FIRST about two minutes ago, so please reload gatool and select your event. You should now see that the Teams tab becomes green after a while (we need to lookup the Community Updates for those teams once we know who they are), and then we can properly render the announce and play-by-play pages. Please confirm that reloading your event restores function.

**Comment by jameslockman** [comment]
Further investigation shows that the work we did to support offline has changed how practice schedule management works. Reviewing now.

**Comment by kleium** [comment]
> We are able to reproduce. It appears that FMS was not reporting team data, so it was impossible to render the announce and play by play pages. This has resolved at FIRST about two minutes ago, so please reload gatool and select your event. You should now see that the Teams tab becomes green after a while (we need to lookup the Community Updates for those teams once we know who they are), and then we can properly render the announce and play-by-play pages. Please confirm that reloading your event restores function.

Unfortunately reloading didn't help. I will be waiting for your response. Thanks again for your interest.

**Comment by jameslockman** [comment]
@kleium We have pushed a new version to [https://beta.gatool.org](https://beta.gatool.org). Can you please load your event and test there?

**Comment by jameslockman** [comment]
@kleium we have pushed the fixes into production.

**Comment by kleium** [comment]
It's working just fine. Cheers.
