### ISSUE TITLE
Play By Play Not Showing Teams In Test Match Offline Mode

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#324]
![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/90eb7413-298d-463f-be76-58f50a22c936)

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/fe3268d3-6884-4822-ae28-19493931a1f0)

**Comment by jameslockman** [comment]
Did you select any teams? You need to do that in Test Match mode.
Can I see the selection interface?

**Comment by jameslockman** [comment]
Unable to reproduce.
