### ISSUE TITLE
Hide Sponsors on Announce after first apperance appears to have no effect

### ISSUE THREAD

**Issue by timtim17** [arthurlockman/gatool-ui#326]
(note, I am looking at a past event, if that has an effect)

<img width="434" alt="image" src="https://github.com/arthurlockman/gatool-ui/assets/6354860/b80f4c20-d04f-40cb-9c86-b2bada355c5f">

**Expected behavior:** With "Show Sponsors on Announce" and "Hide Sponsors on Announce after first appearance" both enabled, I expect the first match for each team to have sponsors on the Announce screen, and any subsequent appearances (in that round (quals/playoffs)?) would have the sponsors hidden. For example, if a team appears in Q2 (first appearance) and Q44, I expect sponsors to be visible on the Announce screen for Q2 and not visible in subsequent matches, including Q44.

**Observed behavior:**

<img width="1134" alt="image" src="https://github.com/arthurlockman/gatool-ui/assets/6354860/7ee1a6ac-aea7-49af-834f-a88050852c58">

<img width="954" alt="image" src="https://github.com/arthurlockman/gatool-ui/assets/6354860/81d1aa01-4ce3-4e73-8598-30ab7ec71397">

Sponsors are still visible on subsequent qualification matches.

If I disable "Show Sponsors on Announce", sponsors are not visible on any matches, including initial appearances.

**Comment by timtim17** [comment]
Based on c5d9ac0cbb9a1dd2dde7ab374bca72a451d82302, seems to actually be working as intended. "Show Sponsors on Announce" will *always* show sponsors, regardless of first appearance. For the past event I was looking at, ranks are present, so if I disable this settings the sponsors are hidden on every match. For an event with no rankings yet, sponsors are shown everywhere, but it seems these will disappear as ranks are populated.

IMO I think the settings are weirdly worded, but otherwise seems like no issue.

**Comment by jameslockman** [comment]
We've made the following update, which will appear after the weekend unless there are other breaking issues:
![FIRST_Game_Announcer_Tool](https://github.com/arthurlockman/gatool-ui/assets/2659225/b8cb0c07-b295-42ff-9d31-2bd3e7de3b7a)
