### ISSUE TITLE
Submit Changes Button Does Nothing

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#333]
When I edit the team information for Team 1885 and select "Submit changes..." nothing happens. When I select "Close without saving changes" it works.

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/84ea8a63-6b6a-4a2d-92fe-f71afa6284ea)

**Comment by jameslockman** [comment]
Does this any other team?

**Comment by WBAucoin** [comment]
Sorry. Will have to check later. I put that laptop away (going on a business trip to Penn State today).

**Comment by WBAucoin** [comment]
No. It happens for this one team (1885). I was able to replicate the
symptoms on the same laptop. I was able to verify that some of the other
teams in the same event do NOT have this issue (I am able to save changes).
I did not check all of the teams to see how widespread this issue might be.

**Comment by jameslockman** [comment]
I have validated that the teams record in gatool cloud is blank. Will restore last good update shortly.

**Comment by jameslockman** [comment]
This team's data won't restore. I can see it in the history, but something is very strange here. We are continuing to investigate.
