### ISSUE TITLE
Reinspection Reminder

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#338]
Consider adding a prompt to the MC/GA team to remind teams to get reinspection after their last qualification matches.

**Comment by timtim17** [comment]
Wonder if there could be value in adding a feature to schedule reminders generally to announce things for a specific event's MC/GA.

For example, this year PNW events have a few scheduled activities at every event -- a senior picture, an alumni picture, and a mentor coffee. But, often we forget to announce these events, or are inconsistent about doing it. Perhaps a reminder could be shown on every nth match, or for a specific match. Messages could be configured with some defaults, such as re-inspection.

Wonder if that's in scope for GATool, and worth the effort.

**Comment by jameslockman** [comment]
This is perhaps covered by #96

**Comment by WBAucoin** [comment]
I don’t think so.  96 <https://github.com/arthurlockman/gatool-ui/issues/96>
 is generic and this is specific. The announcement for reinspection starts
after a team’s last qualification match has completed. This is very similar
to the optional feature you put in to hide sponsors after they have played
one match.

Bill

**Comment by jameslockman** [comment]
Please provide the precise, concise language you would expect in this reminder. Note that this will consume vertical real estate on Play By Play and/or Announce. Here's a first design pass:
![FIRST_Game_Announcer_Tool](https://github.com/arthurlockman/gatool-ui/assets/2659225/ba8117f1-a09a-4406-99bd-80a950c19699)

**Comment by jameslockman** [comment]
@timtim17 @WBAucoin 
This is the current experience. It will display for the last 5 matches of Quals. This also provides infrastructure for additional messaging features, which we will develop at a later date. Will this satisfy the ask? If so, I will push today.

![FIRST_Game_Announcer_Tool](https://github.com/arthurlockman/gatool-ui/assets/2659225/e92136eb-992e-49aa-a0aa-caf5b2d60126)
![FIRST_Game_Announcer_Tool](https://github.com/arthurlockman/gatool-ui/assets/2659225/e5b69f24-071f-4739-a61e-e5ccfe8c83f2)

**Comment by timtim17** [comment]
I think it looks like a good addition, and as you mentioned good infrastructure for more general messages per #96, which I think could be a good future feature.

Would want to see if this satisfies OP's ask.

**Comment by WBAucoin** [comment]
Yes. Looks good.
Did you pick last 5 matches randomly? We can calculate the last match for a
team (or is it not worth the CPU power.

**Comment by jameslockman** [comment]
This is the MVP. We can get fancy later.

**Comment by WBAucoin** [comment]
Concur! Thanks.
