### ISSUE TITLE
Premature Tab Colors and Playoff

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#349]
With no schedule, the FIRST CHS DCMP is showing green for announce & play by play. Additionally, the Playoff Tab/Window is visible and selectable.

![IMG_7319](https://github.com/arthurlockman/gatool-ui/assets/139565335/8e97c592-e855-45e1-afad-853a932673b6)

**Comment by jameslockman** [comment]
Not seeing that here.
![Notification_Center](https://github.com/arthurlockman/gatool-ui/assets/2659225/3c029378-2cab-4020-8b26-150106e6b15f)
