### ISSUE TITLE
Could not load Alliance selection material

### ISSUE THREAD

**Issue by cjculbert** [arthurlockman/gatool-ui#353]
During the FIT Space City Event on Saturday, neither the game announcer or I (the MC) could get gatool to update to the playoffs after we finished the qualification rounds.We tried multiple times during the afternoon, but the tool never showed us finishing the qualification rounds. So far as we could tell, the field was connected to FMS and all of the game software was updating properly.  I can't rule out that we were supposed to do a step to enable that, but neither of us could remember specific instructions like that for gatool.

**Comment by cjculbert** [comment]
I should have noted. We were both using tablets during the event. I was using an iPad accessing gatool via the Chrome browser. The game announcer was on an Android tablet, also using Chrome I think.

**Comment by jameslockman** [comment]
Hi, CJ

We saw several events that had delayed reporting this weekend, resulting in Playoffs not posting data to FIRST or, in the case of WPI, no data from Sunday until after the event finished. Were you able to see up to date event data on The Blue Alliance during the event?

**Comment by cjculbert** [comment]
It was mixed. We saw it on Blue Alliance before we saw it in the gatool, but Blue Alliance was delayed as well. Obviously we were pretty busy and weren’t checking Blue Alliance directly but there were at some reports that Blue Alliance was missing some results so I’m not sure what that might have meant.

**Comment by jameslockman** [comment]
Thank you. This is part of the continuing set of issues related to schedule reports coming out of the FIRST APIs. There is nothing we can do to prevent it, which is why we advised using Test Match mode or uploaded schedules during Playoffs.

**Comment by jameslockman** [comment]
I'm curious: were you able to run Alliance Selection? We were able to do that, but not load a Playoff Schedule.

**Comment by cjculbert** [comment]
Yes,  but since it hadn’t closed out the schedule, we weren’t sure what would happen if we tried to do the alliance selection process in gatool so we didn’t use it in real time. I went back later and did alliance selection and it looked like it worked OK. I couldn’t tell if that ever uploaded.

**Comment by jameslockman** [comment]
Alliance Selection in gatool doesn't get recorded anywhere. The official record is managed by the scorekeeper, so there's no way to do any harm :) Glad you made it through the day! I'm going to close this as complete now.

**Comment by cjculbert** [comment]
Thanks, I appreciate all the help. You guys do awesome work!
