### ISSUE TITLE
Team Data Data Entry Funkiness

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#360]
When trying to edit the HTML-enabled fields in the Team Information, the GUI acts very strange. It will erase any edits made. These symptoms have been observed using Firefox 115.9.0esr (32-bit). I'll try some other browsers also.

**Comment by WBAucoin** [comment]
I was able to replicate the symptoms using Microsoft Edge Version 123.0.2420.65 (Official build) (64-bit). The symptoms only show up when you try to edit the following two (HTML-enabled) fields:

1.  Team Notes for Announce and Play-by-Play Screens (These notes are local notes and do not come from FIRST)
2. Team Notes for the Team Data Screen (These notes are local notes and do not come from FIRST)

**Comment by jameslockman** [comment]
Can you please include a screen shot?

**Comment by WBAucoin** [comment]
Replicated the symptoms in Google Chrome.

**Comment by WBAucoin** [comment]
> Can you please include a screen shot?

I will try. It will have to be a video since it is dynamic.

**Comment by WBAucoin** [comment]
> > Can you please include a screen shot?
> 
> I will try. It will have to be a video since it is dynamic.

Sending via email. I could not upload it to GitHub.

**Comment by jameslockman** [comment]
I have reproduced. Give us a few minutes to fix. We know the reason.

**Comment by WBAucoin** [comment]
Cool. Thanks!

**Comment by jameslockman** [comment]
Should be resolved. Can you test, @WBAucoin ? You may need to clear cache and reload.

**Comment by WBAucoin** [comment]
Testing now. (Just got home from work).

**Comment by jameslockman** [comment]
Build failed. Redeploying now.

**Comment by WBAucoin** [comment]
I was going to say it was not fixed…

**Comment by jameslockman** [comment]
OK to test now.

**Comment by WBAucoin** [comment]
Works properly with Safari on iPad

**Comment by WBAucoin** [comment]
Chrome on iPad still misbehaving. I’ll try to clear it.

**Comment by WBAucoin** [comment]
Chrome on iPad is not fixed. Symptoms remain the same. It is not an app
either.

**Comment by WBAucoin** [comment]
…. It was “bookmarked”. Trying again.

**Comment by WBAucoin** [comment]
I cannot get Chrome to work properly. Same symptoms as before with HTML
enabled fields.

**Comment by WBAucoin** [comment]
HTML fields seem to be working with Crome on iPad now.

**Comment by jameslockman** [comment]
Glad it's working now.
