### ISSUE TITLE
Team Info Not Loading in Google Chrome (Works with Firefox and Safari)

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#364]
Team Info Not Loading in Google Chrome (Works with Firefox and Safari). Tried clearing cache, deleting app. Nothing seems to fix it.

**Comment by jameslockman** [comment]
Switch event.
--
James Lockman
Senior Manager, Digital Media Services
Adobe
***@***.******@***.***>
(917) 284-2268 Mobile
Sent from his iPhone

On Apr 4, 2024, at 7:30 AM, WBAucoin ***@***.***> wrote:

﻿

EXTERNAL: Use caution when clicking on links or opening attachments.


Team Info Not Loading in Google Chrome (Works with Firefox and Safari). Tried clearing cache, deleting app. Nothing seems to fix it.

**Comment by jameslockman** [comment]
This is reproducible but intermittent.

**Comment by jameslockman** [comment]
We changed the way that the Load Team Data button works, so that it now loads the whole Team list and its additional data.
Covered by #367
