### ISSUE TITLE
Playoff Bracket and Emcee Numbers not loading

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#368]
![IMG_7332](https://github.com/arthurlockman/gatool-ui/assets/139565335/e55cb302-d55b-4af4-968d-d9a40f2485fa)
![IMG_7331](https://github.com/arthurlockman/gatool-ui/assets/139565335/a898d829-7039-459f-acf4-f17df2716815)
![IMG_7333](https://github.com/arthurlockman/gatool-ui/assets/139565335/c4b8de77-b3d6-4407-b117-7d167558bc64)

**Comment by jameslockman** [comment]
Not seeing it here. Please clear the browser cache.
<img width="1142" alt="FIRST_Game_Announcer_Tool" src="https://github.com/arthurlockman/gatool-ui/assets/2659225/bb510a94-9d53-498c-92f5-0ac5aae57f65">
<img width="1142" alt="FIRST_Game_Announcer_Tool" src="https://github.com/arthurlockman/gatool-ui/assets/2659225/83b995dd-c28b-4fd6-8f8e-08bcfaf9a1c8">

**Comment by WBAucoin** [comment]
That fixed the iPad. Thanks!
