### ISSUE TITLE
Alliance Selection & Rankings

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#371]
I'm not sure if I can replicate this, but we had a challenge with Alliance Selection in the 2024 FIRST Chesapeake District Championship. We used a rankings printout from the FMS to verify the rankings, through the 16th place team, in the Rankings tab of the gatool. We switched over to the Alliance Section tab and, assuming it was setup correctly, used it until we realized the 3rd (?) alliance captain was wrong. We quickly shifted to using Awards and our hard copy for completing the alliance selection process. Creating an issue to document the experience with no additional information. Now I know to use the Alliance Section tab to verify ranks.

**Comment by jameslockman** [comment]
As noted in the banner, you need to use the RESTART ALLIANCE SELECTION button. 
![IMG_2333](https://github.com/arthurlockman/gatool-ui/assets/2659225/7f569897-2531-44ed-97fc-520bea98b62a)

**Comment by WBAucoin** [comment]
Thanks. Fog of war. Went with the fastest solution. I assumed that the
gatool had one set of rankings which it uses. This leads me to believe that
it has more than one since we found, what appears to us, a second set of
rankings.
I'll chalk this up to one more "on the job" training / lessons learned for
future use.
