### ISSUE TITLE
Playoffs - Highlight Current Match

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#372]
Consider adding a colored rectangle or other visual queue to the user to indicate which match is the current match in the playoffs.

**Comment by jameslockman** [comment]
Are you talking about the Playoff Bracket?

**Comment by WBAucoin** [comment]
Yes

**Comment by jameslockman** [comment]
Would it be sufficient to change the color of the match number? Not sure which color to use, but something like this, which would be relatively easy to implement?
![FIRST_Game_Announcer_Tool](https://github.com/arthurlockman/gatool-ui/assets/2659225/1fe213ab-de7e-479f-bafa-169cdb6a81d5)

**Comment by WBAucoin** [comment]
I think that would work well. I would pick a color that is not already
used. That gold color currently indicates the match winner and might make
it hard to find.
