### ISSUE TITLE
Offline Not Loading Schedules

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#386]
When I switch to ***OFFLINE***, and try to load a schedule, I get "Awaiting team data for •• OFFLINE ••
If your event has finished loading and you don't see a Team List, tap here to try loading your teams again."

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/41b224d1-5571-4989-9084-78fd06a0ebda)

**Comment by WBAucoin** [comment]
Nevermind. Wrong tab!

**Comment by WBAucoin** [comment]
Bonehead user.

**Comment by jameslockman** [comment]
Closing Bonehead issue as solved by bonehead.
