### ISSUE TITLE
Play-by-Play Not Working With Offline Mode

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#392]
Play-by-Play says "No fourth Alliance member" when a schedule is loaded using **OFFLINE** mode. Announce works (but is not showing notes).

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/a2f010fd-56f5-4955-b85a-130940408c76)

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/5dad3288-8fb6-4904-8fa3-d32f26bff884)

**Comment by jameslockman** [comment]
Unable to reproduce. Can you please share your schedule file(s)?

**Comment by jameslockman** [comment]
Please share via upload to this issue. Email attachments do not seem to be supported.

**Comment by WBAucoin** [comment]
[Fake Newton Schedule.xlsx](https://github.com/arthurlockman/gatool-ui/files/14981542/Fake.Newton.Schedule.xlsx)

**Comment by jameslockman** [comment]
Working OK here from your supplied file.
I know I sound like a skipping record, but can you please clear your stored data in your browser and try again? Alternatively, select another event, let it load, then try OFFLINE.

**Comment by WBAucoin** [comment]
Cleared it… and it works. Thanks!

**Comment by WBAucoin** [comment]
Wiping out history in the browser and clearing cache via gatool fixed the issue.

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/994ba957-4e56-4532-ba18-394bfb0a1553)
