### ISSUE TITLE
Add pull down to refresh results

### ISSUE THREAD

**Issue by jameslockman** [arthurlockman/gatool-ui#405]
We added S and F5 key to refresh scores/schedule. These are ineffective on a tablet. Please add pull down to refresh to the Announce, Play By Play, and Emcee pages. Additionally, please add swipe handlers to the Playoff bracket page.

**Comment by WBAucoin** [comment]
The refresh wipes out some of the settings (probable new issue).

**Comment by jameslockman** [comment]
What settings? Can you be more specific? And, are you testing on beta.gatool.org?
This is not finished yet. We are considering making fewer settings long-term sticky, but if it's disruptive, we'll revert them back to persistent storage.
