### ISSUE TITLE
GATool team data base not globally updating with new information

### ISSUE THREAD

**Issue by CitrusDad** [arthurlockman/gatool-ui#437]
I am working on 2 different computers to update the Team notes. But when I saved to upload to the overall data base, I don't see it on my other computer. I can download and upload an Excel file each direction, but why isn't it updating?

**Comment by CitrusDad** [comment]
And why when I change the data locally or upload the Excel data the changes are not showing up in the team summary page, even locally?

**Comment by jameslockman** [comment]
Can you please upload your Excel file? We would like to test on this side. Also, what event are you working at?
If you upload changes via Excel or if you make changes using the Team update form, are you then uploading to GA tool cloud? If those do not go up to the cloud, then they will remain on the Settings page as a pending change. If you have a low bandwidth situation, it’s possible that those did not go up to the cloud, and they may still be sitting on your Settings page. Do check that out.

**Comment by CitrusDad** [comment]
It's updated now. I'm GA at Capital City Classic. I was saving to the
cloud. (I figured out what I was doing wrong on the Team Data page saving.)
However, the update was delayed from working on my other computer last
night and earlier today.

Here's the Excel file I downloaded.

**Comment by jameslockman** [comment]
Hi, Richard.

apparently your email attachment did not make it to github. We'd appreciate it if you could send it to gatool (at) jameslockman (dot) com

**Comment by jameslockman** [comment]
Per email conversation, this appears to be latency rather than a system issue.
